image: i386/ubuntu:xenial

stages:
  - build

variables:
  BYOND_MAJOR: "513"
  BYOND_MINOR: "1527"
  SPACEMAN_DMM_VERSION: "1.5"

before_script:
  - apt-get update -qq
  - apt-get --yes install build-essential unzip libc6:i386 libgcc1:i386 libstdc++6:i386 curl -qq
  - curl "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip
  - unzip byond.zip
  - cd byond
  - make install
  - cd ..
  - curl -LJO "https://github.com/SpaceManiac/SpacemanDMM/releases/download/suite-${SPACEMAN_DMM_VERSION}/dreamchecker" -o dreamchecker
  - chmod +x dreamchecker

build:
    stage: build
    script:
      - ./dreamchecker
      - chmod +rwx ./insert_maps_in_dme.sh
      - ./insert_maps_in_dme.sh
      - DreamMaker ColonialMarinesALPHA.dme
    artifacts:
      paths:
        - ColonialMarinesALPHA.dmb
        - ColonialMarinesALPHA.rsc
      expire_in: 20min
